data_prep:
  raw_dirs_paths:
    - "../mask-rcnn-training-data/raw/subdir1"
  processed_data_path: "../mask-rcnn-training-data/processed/subdir"

train:
  data_path: "../mask-rcnn-training-data/processed/subdir"
  backbone: "resnet101"
  trainable_layers: 3
  batch_size: 16
  initial_lr: 0.02
  momentum: 0.9
  weight_decay: 0.0001
  lr_scheduler: "multistep"
  lr_scheduler_milestones: [16, 22]
  lr_scheduler_step_size: 3 # For StepLR lr scheduler
  lr_scheduler_gamma: 0.1
  lr_scheduler_patience: 2 # For ReduceLROnPlateau lr scheduler
  prefetch_factor: 2
  epochs: 37
  num_workers: 6
  saved_model_path: null
  new_optimizer: false
  new_lr_scheduler: false
  scale_jitter: true
  copy_paste: true
  rnd_photometric_distort: true
  aspect_ratio_group_factor: 3
  amp: true # Use mixed precision training
  # seed: 4002

inference:
  model_path: "./models/model-dir"
  input_data_dir: "../mask-rcnn-training-data/processed/subdir"
