data_prep:
  raw_dirs_paths:
    - "../mask-rcnn-training-data/raw/subdir1"
  processed_data_path: "../mask-rcnn-training-data/processed/subdir"

train:
  data_path: "../mask-rcnn-training-data/processed/subdir"
  backbone: "resnet101"
  trainable_layers: 3
  batch_size: 12
  initial_lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
  lr_scheduler_step_size: 3
  lr_scheduler_gamma: 0.1
  prefetch_factor: 4
  # seed: 4002
  epochs: 10
  num_workers: 12

inference:
  model_path: "./models/model-dir"
  input_data_dir: "../mask-rcnn-training-data/processed/subdir"
